version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    environment:
      ENVIRONMENT: test
      AUTH0_DOMAIN: ariel17.auth0.com
      AUTH0_AUDIENCE: https://railgun.ariel17.com.ar
    working_directory: /go/src/github.com/ariel17/railgun
    steps:
      - checkout
      - run:
          working_directory: /go/src/github.com/ariel17/railgun/api
          command: go mod tidy
      - run:
          working_directory: /go/src/github.com/ariel17/railgun/api
          command: go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload:
          file: api/coverage.txt
